In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df= pd.read_csv('breast_cancer_bd.csv')
df.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   Sample code number           699 non-null    int64 
 1   Clump Thickness              699 non-null    int64 
 2   Uniformity of Cell Size      699 non-null    int64 
 3   Uniformity of Cell Shape     699 non-null    int64 
 4   Marginal Adhesion            699 non-null    int64 
 5   Single Epithelial Cell Size  699 non-null    int64 
 6   Bare Nuclei                  699 non-null    object
 7   Bland Chromatin              699 non-null    int64 
 8   Normal Nucleoli              699 non-null    int64 
 9   Mitoses                      699 non-null    int64 
 10  Class                        699 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 60.2+ KB


In [ ]:
#there are no any nun vlaues in the dataset

In [ ]:
df['Class'].value_counts()

Class
2    458
4    241
Name: count, dtype: int64

In [ ]:
for i in df.columns:
  print(i,df[i].unique())

Clump Thickness [ 5  3  6  4  8  1  2  7 10  9]
Uniformity of Cell Size [ 1  4  8 10  2  3  7  5  6  9]
Uniformity of Cell Shape [ 1  4  8 10  2  3  5  6  7  9]
Marginal Adhesion [ 1  5  3  8 10  4  6  2  9  7]
Single Epithelial Cell Size [ 2  7  3  1  6  4  5  8 10  9]
Bare Nuclei ['1' '10' '2' '4' '3' '9' '7' '?' '5' '8' '6']
Bland Chromatin [ 3  9  1  2  4  5  7  8  6 10]
Normal Nucleoli [ 1  2  7  4  5  3 10  6  9  8]
Mitoses [ 1  5  4  2  3  7 10  8  6]
Class [2 4]


In [ ]:
df[df['Bare Nuclei']=='?'].shape[0]

16

In [ ]:
#column 'Bare Nuclei' has a value of '?' which needs to be filled with another number value
#there are 16 '?' values in 'Bare Nuclei' column

In [ ]:
#lets fill '?' with a nan
df['Bare Nuclei']= df['Bare Nuclei'].replace('?',np.nan)
df[df['Bare Nuclei']=='?'].shape[0]

0

In [ ]:
#now lets replace the nan value with median of the column 'Bare Nuclei'
# First, convert the column to a numeric type
df['Bare Nuclei'] = pd.to_numeric(df['Bare Nuclei'])
df['Bare Nuclei']= df['Bare Nuclei'].fillna(df['Bare Nuclei'].median())
df['Bare Nuclei'].unique()

array([ 1., 10.,  2.,  4.,  3.,  9.,  7.,  5.,  8.,  6.])

In [ ]:
#lets drop non-informative columns, for example column 'Sample code number', since it has
# a high number of unqiue values
df.drop('Sample code number', axis=1, inplace=True)

In [ ]:
df.shape

(699, 10)

In [ ]:
from sklearn.model_selection import train_test_split

#lets separate the features and the targets
x= df.drop('Class', axis=1)
y= df['Class']
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.3)

In [ ]:
#when we use scaling we must use it after splitting the dataset into trianing and test set, to prevent data leakge
#for scaling i will use Standardization
#it is a method of scaling data where the values are transformed to have a mean of 0 and a standard deviation of 1
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

sc= StandardScaler()
x_train_scaled= sc.fit_transform(x_train)
x_test_scaled= sc.transform(x_test)

In [ ]:
#lets train and test a logistic regression model
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

lr= LogisticRegression().fit(x_train_scaled, y_train)
y_pred= lr.predict(x_test_scaled)
y_pred

array([4, 2, 2, 4, 4, 2, 2, 2, 4, 2, 4, 2, 4, 2, 2, 2, 2, 2, 4, 4, 4, 4,
       2, 4, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 2, 2,
       4, 2, 4, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2,
       4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 2, 4, 4, 2, 2, 2, 4, 2, 4, 2, 4, 4,
       4, 4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 4,
       2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2,
       4, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 4,
       2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2,
       2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 4, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2,
       2, 2, 2, 2, 4, 2, 4, 2, 4, 4, 2, 2])

In [ ]:
accuracy= accuracy_score(y_test, y_pred)
accuracy

0.9666666666666667

In [ ]:
cm= confusion_matrix(y_test, y_pred)
cm

array([[132,   0],
       [  7,  71]])

In [ ]:
cf= classification_report(y_test, y_pred)
print(cf)

              precision    recall  f1-score   support

           2       0.95      1.00      0.97       132
           4       1.00      0.91      0.95        78

    accuracy                           0.97       210
   macro avg       0.97      0.96      0.96       210
weighted avg       0.97      0.97      0.97       210



In [ ]:
#the model has a high accuracy score, which makes our predictions accurate
#based on the confusion matrix our model can predict fully accurate of one class (positive class), while having a slightly less inaccuracy when predicting the other class(negative class)
#our f1-score is high implying that Perfect Performance. The model has perfect precision and recall.
#overall our model has a good prediction result, but it might have better prediciton power with some feature engineering and other model error minimizations method